### ISSUE TITLE
Docker image broken

### ISSUE THREAD

**Issue by andrewthad** [tweag/ghc#166]
With the following `stack.yaml` file:

```
packages:
- .
resolver: ghc-8.2
compiler: ghc-8.2
system-ghc: true
docker:
  enable: true
  image: tweag/linear-types
```

The command `stack build` fails with:

```
$ stack build
Preparing to install GHC to an isolated location.
This will not interfere with any system-level installation.
Already downloaded.                
The following executables are missing and must be installed: xz, make
Received ExitFailure 1 when running
Raw command: /usr/bin/docker start -a -i 49297127d9dba26cf90a0445e173901ddcffeae63b410b13fc86f2a428467742
```

**Comment by andrewthad** [comment]
Thanks. I'm just going do a build using the most recent commit on the `linear-types` branch, since it looks like a lot of work has been done on this since version `0.1.9` on dockerhub. I'll leave this open though until you cut the new docker image. Also, thanks for the heads up about the language pragma. That would have taken a while to figure out.

**Comment by aspiwack** [comment]
You'll need it on the tip of `linear-types`.

**Comment by attalos** [comment]
Until a new image exists it also helps to simply create a new one which installs make and xz.

A `Dockerfile` with the content

```
FROM tweag/linear-types

RUN apt-get update
RUN apt-get install -y build-essential xz-utils
```

and compiled with `docker build -t own-linear-types .` does the job.
Then I updated the `resolver` and `compiler` version to `ghc-8.5` and changed the `image` to `own-linear-types` and now it works for me.

**Comment by aspiwack** [comment]
It should be solved in the latest image (0.1.10). I haven't had time to test it yet though.

**Comment by attalos** [comment]
I tried it, but I'm currently not able to get it to work.

When looking into the docker image, `ghc-8.7` seems to be the right compiler version to use.
If i simply set `resolver: ghc-8.7` I run into problems because it does only see ghc-8.4 in the docker image. 
To fix this, I basically excluded `/opt/ghc/8.4.3/bin` from the `PATH`.

My `stack.yaml` now looks like this:

```
resolver: ghc-8.7
compiler: ghc-8.7
packages:
- .
docker:
    enable: true
    image: tweag/linear-types
    env:
        - "PATH=/root/.cabal/bin:/root/.local/bin:/opt/cabal/2.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
```

But now I am stuck with the following error:
```
/home/attalos/.stack/setup-exe-src/setup-mPHDZzAJ.hs:1:1: error:
    Not in scope: ‘mainOverride’
  |
1 | import Distribution.Simple
  | ^

--  While building simple Setup.hs using:
      /usr/local/bin/ghc -rtsopts -threaded -clear-package-db -global-package-db -hide-all-packages -package base -main-is StackSetupShim.mainOverride -package Cabal-2.4.0.1 /home/attalos/.stack/setup-exe-src/setup-mPHDZzAJ.hs /home/attalos/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs -o /home/attalos/.stack/setup-exe-cache/x86_64-linux-dkc68e43cf20ba48282b0ca96c3b2be50e/tmp-Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.7.20181108
    Process exited with code: ExitFailure 1
Received ExitFailure 1 when running
Raw command: /usr/bin/docker start -a -i f9c32607e12b29abd9d75f1c6c9aae3581bcc68cf477341abaa0f2d2d044e61a

```
